//开发环境  bd 的话 不验证登录及权限  将所有路由全都加入；为其他的 则验证登录及权限，只加入匹配的路由
export const dev = 'kf';

// 全局公用数据 - 挂载到全局vue实例上
export const publicObj = {
    projectStatus:{
        '0':'未开始',
        '1':'暂停中',
        '2':'已结束',
        '3':'项目错误',
        '4':'施工中',
        '5':'交付中',
        '6':'维护中',
        '7':'项目大阶段错误'
    },
    orderStatus:{
        '1':'待付款',
        '2':'已付款',
        '3':'部分付款',
        '4':'已退款',
        '5':'已取消',
        '6':'部分退款'
    },
    payType:{
        '1':'对公转账',
        '2':'微信',
        '3':'支付宝',
        '4':'现金',
        '5':'其他'
    },
    sendStatus:{
        '1':'待出库',
        '2':'已出库'
    },
    runStatus:{
        '1':'运行中',
        '2':'已停止'
    },
    lineColor:{
        '1':'#633ce3',
        '2':'#00c7db',
        '3':'#ffe14d',
        '4':'#348a31'
    },
    defaultThreshold:[
        {
            type:'formaldehyde',
            name:"甲醛",
            rangeInfo:{
                max:0.3,
                min:0,
                step:0.001
            }
        },
        {
            type:'TVOC',
            name:'TVOC',
            rangeInfo:{
                max:1,
                min:0,
                step:0.001
            }
        },
        {
            type:'PM25',
            name:'PM2.5',
            rangeInfo:{
                max:100,
                min:0,
                step:0.001
            }
        },
        {
            type:'CO2',
            name:'CO2',
            rangeInfo:{
                max:1500,
                min:0,
                step:0.01
            }
        },
        {
            type:'temperature',
            name:'温度',
            rangeInfo:{
                max:50,
                min:-50,
                step:0.1
            }
        },
        {
            type:'humidity',
            name:'湿度',
            rangeInfo:{
                max:100,
                min:0,
                step:1
            }
        }
    ],
    productList:[
        {
            id:1,
            name:'全能空气净化器',
            price:'2888.00'
        }
    ]
}
